from scripts.imports import *
from scripts.show_tracks import *
from scripts.track_pairs import *
from scripts.DW import *
import geopandas as gpd
from shapely.geometry import Point, box as shapely_box
from scipy.optimize import least_squares, minimize
import scipy.sparse.linalg
from sklearn.metrics import r2_score, root_mean_squared_error, mean_absolute_error
from scripts.odr import *
from scipy.stats import zscore, norm
from sklearn.linear_model import LinearRegression
from sklearn.covariance import EllipticEnvelope
from sklearn.neighbors import LocalOutlierFactor
import random

import sys
import gc

sys.path.insert(1,'/home/s1803229/src/PhoREAL')
# sys.path.insert(1,'C:/Users/s1803229/Documents/PhoREAL')

from phoreal.reader import get_atl03_struct, get_atl08_struct
from phoreal.binner import rebin_atl08

import warnings
warnings.filterwarnings("ignore", module="sklearn.neighbors._lof")
warnings.filterwarnings("ignore", module="scipy.interpolate._interpolate")

def divide_arrays(X, Y, n=2):
    combined = list(zip(X, Y))
    combined.sort(key=lambda tup: tup[0])
    midpoint = len(combined) // n
    
    lower_half = combined[:midpoint]
    upper_half = combined[midpoint*(n-1):]

    lower_X, lower_Y = zip(*lower_half)
    upper_X, upper_Y = zip(*upper_half)
    
    return lower_X, lower_Y, upper_X, upper_Y

def intercept_from_slope_and_point(slope, point):
    x1, y1 = point
    intercept = y1 - slope * x1
    return intercept

def find_slope_and_intercept(x1, y1, x2, y2):
    slope = (y2 - y1) / (x2 - x1)
    intercept = y1 - slope * x1
    return slope, intercept

def starting_intercept(X,Y,n):
    if len(Y) == 1:
        slope = -.3
        intercept = intercept_from_slope_and_point(slope, (list(X)[0],list(Y)[0]))
    else:
        lower_X, lower_Y, upper_X, upper_Y = divide_arrays(X, Y, n)

        y1 = np.median(lower_Y)
        y2 = np.median(upper_Y)
        x1 = np.median(lower_X)
        x2 = np.median(upper_X)

        if x1 == x2:
            slope = -.3
            intercept = intercept_from_slope_and_point(slope, (x1,y1))
        else:
            slope, intercept = find_slope_and_intercept(x1, y1, x2, y2)
            if slope > -0.01:
                slope = -0.01
            if slope < -100:
                slope = -100
            intercept = intercept_from_slope_and_point(slope, (np.mean([x1,x2]),np.mean([y1,y2])))

        return intercept, slope

def parse_filename_datetime(filename):
    filename_only = filename.split('/')[-1]
    atl03_index = filename_only.find('ATL03_')
    atl08_index = filename_only.find('ATL08_')

    # Determining the split index based on which string appears first or if neither is found
    split_index = min(filter(lambda x: x >= 0, [atl03_index, atl08_index]))

    # Extracting yyyymmddhhmmss part
    date_str = filename_only[split_index + 6:split_index + 20]

    datetime_obj = datetime.strptime(date_str, '%Y%m%d%H%M%S')
    return datetime_obj

def datetime_to_title(datetime_obj):
    return datetime_obj.strftime('%B %d, %Y, %H:%M:%S')

def datetime_to_date(datetime_obj):
    return datetime_obj.strftime('%d/%m/%Y')

def make_box(coords, width_km=25, height_km=25):
    # Convert width and height from kilometers to degrees
    km_per_degree_lat = 111  # Kilometers per degree of latitude
    km_per_degree_lon = 111 * np.cos(np.radians(coords[1]))  # Kilometers per degree of longitude at given latitude

    # Convert the input width and height from kilometers to degrees
    width_deg = width_km / km_per_degree_lon
    height_deg = height_km / km_per_degree_lat

    # Create the bounding box using converted degrees
    polygon = gpd.GeoDataFrame(
        geometry=[
            shapely_box(
                coords[0] - width_deg, coords[1] - height_deg, 
                coords[0] + width_deg, coords[1] + height_deg
            )
        ], 
        crs="EPSG:4326"
    )
    
    return polygon

def non_negative_subset(asr_list):
    cleaned_data = []
    
    for item in asr_list:
        if isinstance(item, pd.Series):
            cleaned_data.extend(item.values)
        elif isinstance(item, list) and item == [-1]:
            continue
        else:
            cleaned_data.extend([x for x in item])
    
    return np.array(cleaned_data)

def safe_mean(arr):
    if arr.size == 0:  # Check if the array is empty
        return np.nan
    else:
        return np.mean(arr)

def flatten_structure(structure):
    flat_list = []
    if isinstance(structure, (list, tuple, np.ndarray)):
        for item in structure:
            flat_list.extend(flatten_structure(item))
    else:
        flat_list.append(structure)
    return flat_list

def plot(df, ax):
    """
    Plot function for the ground tracks.
    
    df - Dataframe generated by get_atl03_struct
    ax - Axis on which to plot the relevant figure
    """
    class_dict = {-1: {'color':cmap(0.98),
                       'name':'Unclassified'},
                   0: {'color':cmap(0.2),
                       'name':'Noise'},
                   1: {'color':cmap(0.8),
                       'name':'Ground'},
                   2: {'color':cmap(0.4),
                       'name':'Canopy'},
                   3: {'color':cmap(0.6),
                       'name':'Top of canopy'}}

    ymin = None
    ymax = None
    
    if 'classification' in df.columns:
        for c in np.unique(df.classification):
            mask = df.classification==c
            ax.scatter(df[mask].lat_ph,
                       df[mask].h_ph,
                       color=class_dict[c]['color'],
                       label=class_dict[c]['name'],
                       s = 3)

            ax.legend(loc='best')
            if c != -1:
                if ymin == None:
                    ymin = min(df[mask].h_ph)
                    ymax = max(df[mask].h_ph)
                else:
                    ymin = min(ymin,min(df[mask].h_ph))
                    ymax = max(ymax,max(df[mask].h_ph))
        ax.set_ylim(ymin-0.02*(ymax-ymin),ymax+0.02*(ymax-ymin))
            
    else:
            ax.scatter(df.lat_ph,
                      df.h_ph,
                      s = 3)
    ax.set_xlabel('Latitude (°)')
    ax.set_ylabel('Elevation (m)')
    return

def plot_pvpg(
    coefs, colors, title_date, X, Y, xx, yy,
    beam=None, file_index=None, data_quality=0, graph_detail=1, atl03s=None,
    canopy_frac=None, terrain_frac=None, coords=None):
    # config the data_quality
    """
    Combined plotting function for pvpg_parallel.

    Parameters
    ----------
    coefs : array-like
        Optimized parameters. coefs[0] is the shared slope, and coefs[1+i]
        is the intercept term for the i-th available beam.
    colors : list
        Beam indices minus one, used for consistent beam colouring.
    title_date : str
        Datetime string for the ICESat-2 overpass.
    X, Y : list of arrays
        Eg and Ev data for each successfully read beam.
    xx, yy : list-like
        Additional plotted data by beam index.
    beam : list, optional
        List of beam numbers to show, e.g. [3, 4]. If None, all available beams are shown.
    file_index : int, optional
        File index to include in the title.
    data_quality : int, optional
        Index into title_color.
    graph_detail : int, optional
        1 = just the main scatter/regression plot
        2 = just the groundtrack subplots
        3 = groundtrack subplots + main scatter/regression plot
    atl03s : list, optional
        Required if graph_detail == 2. ATL03 objects for groundtrack plotting.
    canopy_frac : list, optional
        Canopy fraction by beam index, used in subplot titles when graph_detail == 2 or 3.
    terrain_frac : list, optional
        Terrain fraction by beam index, used in subplot titles when graph_detail == 2 or 3.
    coords : unused, optional
        Kept only for compatibility with your old function signature.
    """

    title_color = ['black', 'red']
    beam_names = [f"Beam {i}" for i in range(1, 7)]

    if graph_detail == 1:
        fig = plt.figure(figsize=(10, 6))
        ax_main = fig.add_subplot(111)
        axes = None
    elif graph_detail != 0:
        fig = plt.figure(figsize=(10, 12))
        if graph_detail == 2:
            ax1 = fig.add_subplot(331)
            ax2 = fig.add_subplot(332)
            ax3 = fig.add_subplot(334)
            ax4 = fig.add_subplot(335)
            ax5 = fig.add_subplot(337)
            ax6 = fig.add_subplot(338)
            ax_main = fig.add_subplot(133)
        else:
            ax1 = fig.add_subplot(321)
            ax2 = fig.add_subplot(322)
            ax3 = fig.add_subplot(323)
            ax4 = fig.add_subplot(324)
            ax5 = fig.add_subplot(325)
            ax6 = fig.add_subplot(326)
            ax_main = None
        axes = [ax1, ax2, ax3, ax4, ax5, ax6]

    # Title
    if file_index is not None:
        fig.suptitle(
            title_date + ' - N = ' + str(file_index),
            fontsize=16 if graph_detail == 2 else 18,
            color=title_color[data_quality]
        )
    else:
        fig.suptitle(
            title_date,
            fontsize=16 if graph_detail == 2 else 18,
            color=title_color[data_quality]
        )

    # Groundtrack Displays
    if graph_detail in (2, 3):
        if atl03s is None:
            raise ValueError("atl03s must be provided when graph_detail is 2 or 3")
        for i, c, atl03 in zip(np.arange(len(colors)), colors, atl03s):
            if (canopy_frac is not None) and (terrain_frac is not None):
                axes[c].set_title(
                    f"{beam_names[c]} - TF = {round(terrain_frac[c], 2)}, CF = {round(canopy_frac[c], 2)}"
                )
            elif canopy_frac is not None:
                axes[c].set_title(f"{beam_names[c]} - CF = {round(canopy_frac[c], 2)}")
            elif terrain_frac is not None:
                axes[c].set_title(f"{beam_names[c]} - TF = {round(terrain_frac[c], 2)}")
            else:
                axes[c].set_title(f"{beam_names[c]}")

            plot(atl03, axes[c])

    # pv/pg Plot
    if graph_detail in (1, 2):
        for i, c in enumerate(colors):
            if (beam is not None) and ((c + 1) not in beam):
                continue

            ax_main.scatter(X[i], Y[i], s=7 if graph_detail == 1 else 5,
                           color=cmap3(2 * c + 1), marker='o')
            ax_main.scatter(xx[c], yy[c], s=7 if graph_detail == 1 else 5,
                           color=cmap3(2 * c), marker='o')

            ax_main.plot(
                np.array([0, 12]),
                model([coefs[0], coefs[1 + i]], np.array([0, 12])),
                label=f"Beam {int(c + 1)}",
                color=cmap3(2 * c),
                linestyle='--',
                zorder=3,
                linewidth=2 if graph_detail == 1 else 1.5
            )

            ax_main..annotate(
            r'$\rho_v/\rho_g \approx {:.2f}$'.format(-coefs[0]),
            xy=(.14, .967) if graph_detail == 1 else (.35, .98),
            xycoords='axes fraction',
            ha='right',
            va='top',
            fontsize=14 if graph_detail == 1 else 8,
            bbox=dict(
                boxstyle="round,pad=0.3",
                edgecolor="black",
                facecolor="white"
            )
        )

        if graph_detail == 1:
            ax_main.set_xlabel('Eg (returns/shot)', fontsize=14)
            ax_main.set_ylabel('Ev (returns/shot)', fontsize=14)
            ax_main.set_xlim(0, 9)
            ax_main.set_ylim(0, 9)
            ax_main.tick_params(axis='both', labelsize=16)
            ax_main.legend(loc='best', fontsize=16)
        else:
            ax_main.set_title("Ev/Eg Rates", fontsize=8)
            ax_main.set_xlabel('Eg (returns/shot)')
            ax_main.set_ylabel('Ev (returns/shot)')
            ax_main.set_xlim(0, 8)
            ax_main.set_ylim(0, 40)
            ax_main.legend(loc='best')

    plt.tight_layout(rect=[0, 0, 1, 0.97])
    plt.show()
    return

def parallel_model(params, x):
    common_slope, *parallel = params
    # Get all columns starting with 'Beam'
    beam_columns = [col for col in x.columns if col.startswith('Beam')]
    return common_slope*x['Eg'] + np.dot(x[beam_columns], parallel)

def parallel_residuals(params, x, y, model=parallel_model, w=[1.0, 0.25]):
    # config the w
    common_slope = params[0]
    model_output = model(params, x)
    residuals = (y.T.values[0] - model_output) / np.sqrt(1 + common_slope**2)

    beam_columns = [col for col in x.columns if col.startswith('Beam')]

    weights = []
    for i, col in enumerate(beam_columns):
        beam_number = int(col.split('Beam')[-1])  # Extract beam number
        weight = w[0] if beam_number % 2 != 0 else w[1]  # Weight: 1 if odd, 1/4 if even
        weights.append(weight)
    weighted_residuals = residuals.copy()*np.dot(x[beam_columns], weights)

    prior_penalty = 0

    residuals_and_penalty = np.append(weighted_residuals, prior_penalty)
    return residuals_and_penalty

def parallel_odr(dataset, intercepts, maxes, init = -1, lb = -100, ub = -1/100,
                 model = parallel_model, res = parallel_residuals,
                 loss='linear', f_scale=.1, outlier_removal = False, method='normal', w=[1.0,0.25]):
    # config the init, lb, ub, loss, f_scale, outlier_removal, method, and w
    """
    Performs the parallel orthogonal distance regression on the given dataset.
    
    dataset - Pandas Dataframe with columns Eg, Ev, and Beam _ for each beam with data.
    maxes - Array that holds the initial y_intercept guess for each beam. If only Beams 5 and 6 made it, then there are only two values in this array.
    init - Initial slope guess
    lb - Lower bound constraint for slope
    ub - Upper bound constraint for slope
    model - Model to estimate Ev and Eg.
    res - Residuals to put into least_squares function
    loss - Loss function in regression
    f_scale - f_scale parameter for least_squares, affects how much it cares about outliers.
    """
    cats = dataset.shape[1] - 5

    a = [lb] + [0]*cats
    b = [ub] + maxes
    bounds = (a,b)
    initial_params = [init] + intercepts

    beam_columns = [col for col in dataset.columns if 'Beam' in col]
    filtered_data = []
    full_data = []
    data_quantity = 0

    for beam in beam_columns:
        beam_data = dataset[dataset[beam] == True][['Eg', 'Ev', 'layer_flag', 'msw_flag', 'cloud_flag_atm'] + beam_columns].copy()

        if outlier_removal = False:
            beam_data['Outlier'] = 1
            full_data.append(beam_data[['Eg', 'Ev', 'layer_flag', 'msw_flag', 'cloud_flag_atm', 'Outlier'] + beam_columns])
            continue

        if len(beam_data) >= 2:
            if outlier_removal < 1:
                envelope = EllipticEnvelope(contamination=outlier_removal, random_state=42)
                envelope.fit(beam_data[['Eg', 'Ev']])
                beam_data['Outlier'] = envelope.predict(beam_data[['Eg', 'Ev']])
                beam_filtered = beam_data[beam_data['Outlier'] == 1]
            elif outlier_removal >= 2:
                outlier_flags = np.zeros(len(beam_data), dtype=bool)
                n = int(max(1,min(outlier_removal,len(beam_data)-3))) #config the 3
                lof = LocalOutlierFactor(n_neighbors=n, contamination='auto')
                preds = lof.fit_predict(beam_data[['Eg', 'Ev']])
                outlier_flags = (preds == -1) # this used to be |=, this fix could create bug?
                beam_data['Outlier'] = np.where(outlier_flags, -1, 1)
                beam_filtered = beam_data[beam_data['Outlier'] == 1]
            else:
                beam_filtered = beam_data
        else:
            beam_filtered = beam_data

        filtered_data.append(beam_filtered[['Eg', 'Ev', 'layer_flag', 'msw_flag', 'cloud_flag_atm'] + beam_columns])
        full_data.append(beam_data[['Eg', 'Ev', 'layer_flag', 'msw_flag', 'cloud_flag_atm', 'Outlier'] + beam_columns])
        data_quantity = max(data_quantity, len(beam_data))

    full_dataset = pd.concat(full_data).reset_index(drop=True)
    if outlier_removal != False:
        filtered_dataset = pd.concat(filtered_data).reset_index(drop=True)
        dataset = filtered_dataset.copy()

    X = dataset.drop(columns=['Ev', 'layer_flag', 'msw_flag', 'cloud_flag_atm'])
    Y = dataset[['Ev']]

    if loss == 'linear':
        params = least_squares(parallel_residuals, x0=initial_params, args=(X, Y, model, False, w), loss = loss, bounds = bounds)
    else:
        params = least_squares(parallel_residuals, x0=initial_params, args=(X, Y, model, False, w), loss = loss, bounds = bounds,
                               f_scale=f_scale, ftol=1e-15, xtol=1e-15, gtol=1e-15)

    return params.x, dataset, full_dataset