parallel_blocks:
  w: [1.0, 0.25]

  slope_init: -1
  slope_lb: -100
  slope_ub: -0.01

  loss: linear
  f_scale: 0.1

  outlier_removal: False

  roi_half_width: 4
  roi_half_height: 4
  small_box_side: 1

  alt_thresh:
  insufficient_data_threshold: 1